In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## butter sales

In [2]:
np.random.random(0)
sales_amount = np.random.randint(20,size=(5,3))
sales_amount

array([[ 8, 10, 17],
       [10, 16,  2],
       [10,  4,  7],
       [16, 17,  9],
       [15, 10,  6]])

In [3]:
#Creating dataframe

weekly_sales = pd.DataFrame(sales_amount,index = ["mon","tue","wed","thu","fri"],
                           columns = ["Almonad","peanut","cashew"])

weekly_sales

Almonad  peanut  cashew
mon        8      10      17
tue       10      16       2
wed       10       4       7
thu       16      17       9
fri       15      10       6

In [4]:
weekly_sales.columns = weekly_sales.columns.str.capitalize()
weekly_sales.index = weekly_sales.index.str.capitalize()

In [5]:
weekly_sales

Almonad  Peanut  Cashew
Mon        8      10      17
Tue       10      16       2
Wed       10       4       7
Thu       16      17       9
Fri       15      10       6

In [6]:
prices = np.array([10,9,12])
prices

array([10,  9, 12])

In [7]:
butter_prices = pd.DataFrame(prices.reshape(1,3),index = ["Prices"],
                           columns = ["Almonad","peanut","cashew"])

In [8]:
butter_prices

Almonad  peanut  cashew
Prices       10       9      12

In [9]:
weekly_sales.shape

(5, 3)

In [10]:
butter_prices.shape

(1, 3)

In [11]:
total = np.dot(weekly_sales,butter_prices.T)

In [12]:
total

array([[374],
       [268],
       [220],
       [421],
       [312]])

In [13]:
total_cost=np.sum(total)

In [14]:
total_cost

1595

In [15]:
weekly_sales["Total"] = total

In [16]:
weekly_sales

Almonad  Peanut  Cashew  Total
Mon        8      10      17    374
Tue       10      16       2    268
Wed       10       4       7    220
Thu       16      17       9    421
Fri       15      10       6    312